In [23]:
import numpy as np
from numba import jit

In [40]:
a = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6], [4,5,6,7]])
b = np.random.randint(1,7, size = (100,100))
c = np.random.randint(1,7, size = (1000,1000))

aout,bout,cout = np.zeros_like(a),np.zeros_like(b),np.zeros_like(c)

x_win = 1
y_win = 1

In [41]:
def mw_mean(in_arr,out_arr,x_win,y_win):
    xn,yn = in_arr.shape
    for x in range(xn):
        xmin = max([0,x - x_win])
        xmax = min([xn, x + x_win + 1])
        for y in range(yn):
            ymin = max([0,y - y_win])
            ymax = min([yn, y + y_win + 1])
            print (f"{xmin}:{xmax}, {ymin}:{ymax}")
            out_arr[x,y] = in_arr[xmin:xmax, ymin:ymax].mean()
    return out_arr



@jit("i4[:,:](i4[:,:],i4[:,:],i4,i4)", nopython = True)
def mw_mean_numba(in_arr,out_arr,x_win,y_win):
    xn,yn = in_arr.shape
    for x in range(xn):
        xmin = max(0,x - x_win)
        xmax = min(xn, x + x_win + 1)
        for y in range(yn):
            ymin = max(0,y - y_win)
            ymax = min(yn, y + y_win + 1)

            out_arr[x,y] = in_arr[xmin:xmax, ymin:ymax].mean()
    return out_arr

In [42]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [44]:
mw_mean(a, aout, x_win, y_win)

0:2, 0:2
0:2, 0:3
0:2, 1:4
0:2, 2:4
0:3, 0:2
0:3, 0:3
0:3, 1:4
0:3, 2:4
1:4, 0:2
1:4, 0:3
1:4, 1:4
1:4, 2:4
2:4, 0:2
2:4, 0:3
2:4, 1:4
2:4, 2:4


array([[2, 2, 3, 4],
       [2, 3, 4, 4],
       [3, 4, 5, 5],
       [4, 4, 5, 6]])

In [48]:
a[0:2, 0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
(1+2+2+3)/4

2.0

In [49]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [50]:
window = np.ones((2,2))/4

In [55]:
from scipy.signal import convolve2d

In [56]:
convolve2d(a,window, 'valid')

array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])