In [3]:
### Package Import
import sys
import os
base_dir = os.environ['GEMS_HOME']
project_path = os.path.join(base_dir, 'python-refactor')
sys.path.insert(0, project_path)

from Code.utils import matlab
#from Code.utils import helpers

import scipy.io as sio
import numpy as np
import glob
import time
import h5py

### Setting path
omi_path = os.path.join(project_path, 'Data', 'Raw', 'OMI')
data_path = os.path.join(project_path, 'Data')
# addpath(genpath([path_data,'/matlab_func/']))                     % Add the path of external function (matlab_func) folder with subfolders

### Setting period
YEARS = [2016] # YEARS = range(2015, 2017+1)

In [ ]:
### OMNO2d
for yr in YEARS:
    curr_path = os.path.join(omi_path, 'L3', 'OMNO2d', str(yr))
    list_char = glob.glob(os.path.join(curr_path, '*.he5'))
    list_char = [os.path.basename(f) for f in list_char]
    
    doy_000 = matlab.datenum(f'{yr}0000')
    list_doy = [int(x[19:23])+int(x[24:28])-doy_000 for x in list_char]
    list_doy = [1,2]
    if yr%4==0:
        days = 366
    else:
        days = 365
    
    # Size is too big to create. data_yr = np.full((1036800, days), np.nan)
    # np.memmap create zeros array.
    ccc
    for i in range(len(list_char)):
        # data = matlab.h5read(list_char[i], '/HDFEOS/GRIDS/ColumnAmountNO2/Data Fields/ColumnAmountNO2CloudScreened')
        data = matlab.h5read(os.path.join(curr_path, list_char[i]), '/HDFEOS/GRIDS/ColumnAmountNO2/Data Fields/ColumnAmountNO2TropCloudScreened')
        data = data.astype(np.float64)
        data[data<=-1.2676506e+30] = np.nan # Assign NaN value to pixel that is out of valid range
        data = data * 3.7216e-17                                 # molec/cm2 to DU
        data_yr[:, list_doy[i]] = data.flatten() # Put daily data as column vector
        print (f'OMNO2d_{yr}_{list_doy[i]:03d}')
        data_yr[:, list_doy[i]][data_yr[:, list_doy[i]]==np.nan] = -9999
    hdf5_store.close()
    break
    #data_yr[np.isnan(data_yr)]=-9999
    prefix = np.tile('d', [days, 1]) # prefix for header
    header = map(lambda x: f'{x:03d}', prefix) # header = cellstr([prefix,num2str([1:days]','%03i')]);
    sio.savemat(os.path.join(data_path, 'pre', 'OMI_tempConv', f'OMNO2d_{yr}_DU.mat'), mdict={'data_yr':data_yr})

In [ ]:
np.where(data_yr[:, list_doy[i]]==np.nan, )

In [1]:
tmp_arr = data_yr[:, list_doy[i]]
data_yr[:, list_doy[i]] = np.where(tmp_arr==np.nan, np.nan, tmp_arr)

NameError: name 'data_yr' is not defined

In [47]:
days = 5
nrows, ncols = 10, days
hdf5_store = h5py.File("./cache.hdf5", "w")
data_yr = hdf5_store.create_dataset("results", (nrows, ncols), fillvalue=np.nan, dtype='float64')

In [48]:
import copy

In [49]:
x = data_yr[:, 0]
x = np.isnan(x)
data_yr[:, 0][x] = -9999

In [50]:
data_yr[:, 0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [45]:
data_yr[:, 0][True, True, R]

nan

In [34]:
type(data_yr[0][0])

numpy.float64

In [37]:
np.isnan(data_yr[0][0])

True

In [21]:
data_yr[:, 0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [17]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [19]:
    
    list_doy = [1,2]

In [22]:
data_yr[:, list_doy[i]][data_yr[:, list_doy[i]]==np.nan] = -9999

In [16]:
days = 366
nrows, ncols = 1036800, days
tStart = time.time()
data_yr = np.memmap('memmapped.dat', dtype=np.float64, 
                    mode='w+', shape=(nrows, ncols))

In [58]:
import h5py

days = 366
nrows, ncols = 1036800, days
hdf5_store = h5py.File("./cache.hdf5", "w")
data_yr = hdf5_store.create_dataset("results", (nrows, ncols), fillvalue=np.nan, dtype='float64')

In [61]:
data_yr[data_yr==np.nan] = -9999

In [46]:
hdf5_store.close()

In [11]:

# do something...
results[100, 25, 1, 4] = 42

This creates a file cache.hdf5 which will contain the data. create_dataset gets us an object that we can treat just like a numpy array (at least most of the time). Additionally we get a file that contains this array and that we can access from other scripts:

hdf5_store = h5py.File("./cache.hdf5", "r")

print hdf5_store["results"][100, 25, 1, 4] # 42.0

MemoryError: Unable to allocate array with shape (1036800, 366) and data type float64

In [60]:
data_yr[:,0].shape

(1036800,)

In [59]:
data_yr.shape

(1036800, 366)

In [54]:
sum(sum(data==0))

0

In [47]:
data = data.astype(np.float64)

In [48]:
data.T.flatten()

array([-4.71768855e+13, -4.71768855e+13, -4.71768855e+13, ...,
       -4.71768855e+13, -4.71768855e+13, -4.71768855e+13])

In [49]:
data_yr[:, 1] = data.T.flatten()

In [4]:
yr = 2016
curr_path = os.path.join(omi_path, 'L3', 'OMNO2d', str(yr))
list_char = glob.glob(os.path.join(curr_path, '*.he5'))
list_char = [os.path.basename(f) for f in list_char]
    
i=0
data = matlab.h5read(os.path.join(curr_path, list_char[i]), '/HDFEOS/GRIDS/ColumnAmountNO2/Data Fields/ColumnAmountNO2TropCloudScreened')

In [6]:
data.min()

-1.2676506e+30

In [7]:
data.max()

5.688038e+16

In [8]:
data2 = data[:] * 3.7216e-17

In [10]:
data2.min()

-47176885000000.0

In [11]:
data2.max()

2.1168602

In [12]:
data[data<=-1.2676506e+30] = -9999

In [13]:
data = data * 3.7216e-17;  

In [38]:
list_doy[i] = 1

In [44]:
np.ones((1036800, days), dtype='uint8')

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [43]:
np.full((1036800, days), np.nan, dtype='uint8')

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [11]:

### OMSO2e
for yr in YEARS:
    os.chdir(os.path.join(omi_path, 'L3_grid', 'OMSO2e', str(yr)))
    list_char = matlab.dir('.', '.he5')
    doy_000 = datenum(f'{yr}0000')
    list_doy = map(lambda x: x[19:23]+x[23:28]-doy_000, list_char)
    if yr%4==0:
        days = 366
    else:
        days = 365
    
    data_yr = np.full(1036800, np.nan)
    for i in range(len(list_char)):
        data = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount SO2/Data Fields/ColumnAmountSO2_PBL')
        rcf = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount SO2/Data Fields/RadiativeCloudFraction')
        sza = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount SO2/Data Fields/SolarZenithAngle')
    
        # Assign NaN value to pixel that is out of valid range
        data = np.float64(data) # data[data<=-1.2676506e+30]=np.nan;
        rcf = np.float64(rcf) # rcf[rcf<=-1.2676506e+30]=np.nan;
        sza = np.float64[sza] # sza[sza<=-1.2676506e+30]=np.nan;
        
        # Filtering SO2_VCD with the condition of radiative cloud fraction and
        # solar zenith angle
        data2 = data;
        data2[rcf>=0.3]=np.nan;
        data2[sza>=78]=np.nan;
        
        data_yr[:, list_doy(i)] = data2.flatten() # Put daily data as column vector
        print (f'OMSO2e_m_{yr}_{list_doy[i]:03d}')
    data_yr[np.isnan(data_yr)]=-9999;
    prefix = np.tile('d', [days, 1]) # prefix for header
    header = map(lambda x: f'{x:03d}', prefix) # header = cellstr([prefix,num2str([1:days]','%03i')]);
    sio.savemat(os.path.join(data_path, 'OMI_L3_tempConv', f'OMSO2d_{yr}_DU.mat'), mdict={'data_yr':data_yr})

### OMDOAO3e
for yr in YEARS:
    tStart = time.time()
    os.chdir(os.path.join(omi_path, 'L3_grid', 'OMDOAO3e', str(yr)))
    list_char = matlab.dir('.', '.he5')
    doy_000 = datenum(f'{yr}0000')
    list_doy = map(lambda x: x[19:23]+x[23:28]-doy_000, list_char)
    if yr%4==0:
        days = 366
    else:
        days = 365
    
    data_yr = np.full(1036800, np.nan)
    for i in range(len(list_char)):
        data = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/ColumnAmountO3/Data Fields/ColumnAmountO3')
        cf = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/ColumnAmountO3/Data Fields/CloudFraction')
        sza = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/ColumnAmountO3/Data Fields/SolarZenithAngle')
    
        # Assign NaN value to pixel that is out of valid range
        data = np.float64(data) # data[data<=-1.2676506e+30]=np.nan;
        cf = np.float64(cf) # rcf[rcf<=-1.2676506e+30]=np.nan;
        sza = np.float64[sza] # sza[sza<=-1.2676506e+30]=np.nan;
        
        # Filtering SO2_VCD with the condition of radiative cloud fraction and
        # solar zenith angle
        data2 = data;
        data2[cf>=0.3]=np.nan;
        data2[sza>=78]=np.nan;
        
        data_yr[:, list_doy(i)] = data2.flatten() # Put daily data as column vector
        print (f'OMDOAO3e_m_{yr}_{list_doy[i]:03d}')
    data_yr(isnan(data_yr))=-9999;
    prefix = np.tile('d', [days, 1]) # prefix for header
    header = map(lambda x: f'{x:03d}', prefix) # header = cellstr([prefix,num2str([1:days]','%03i')]);
    sio.savemat(os.path.join(data_path, 'OMI_L3_tempConv', f'OMSO2d_{yr}_DU.mat'), mdict={'data_yr':data_yr})
    tElapsed = time.time() - tStart
    print (f'{tElapsed} second')

### OMHCHOG
for yr in YEARS:
    os.chdir(os.path.join(omi_path, 'L2_grid', 'OMHCHOG', str(yr)))
    list_char = matlab.dir('.', '.he5')
    doy_000 = datenum(f'{yr}0000')
    list_doy = map(lambda x: x[19:23]+x[23:28]-doy_000, list_char)
    if yr%4==0:
        days = 366
    else:
        days = 365
    
    data_yr = np.full(1036800, np.nan)
    for i in range(len(list_char)):
        data = mathlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount HCHO/Data Fields/ColumnAmountDestriped')
        # Assign NaN value to pixel that is out of valid range
        data = np.float64(matlab.permute(data,[2,1,3]))
        data[data<=-1.0e+30] = np.nan
        VCD = data * 3.7216e-17                                  # molec/cm2 to DU
        
        QA = matlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount HCHO/Data Fields/MainDataQualityFlag')
        QA = np.float64(permute(QA, [2,1,3]))
        QA[QA<=-30000] = np.nan
        
        sza = matlab.h5read(list_char[i],'/HDFEOS/GRIDS/OMI Total Column Amount HCHO/Data Fields/SolarZenithAngle')
        sza = np.float64(matlab.permute(sza,[2,1,3]))
        sza[sza<=-1.0e+30] = np.nan
        
        VCD_filtered = np.zeros(VCD.shape)
        for k in range(15):
            VCD_temp = VCD[:,:,k]
            QA_temp = QA[:,:,k]
            sza_temp = sza[:,:,k]
            
            VCD_temp[QA_temp!=0] = np.nan #  Good columns (0) / Suspect columns (1) / Bad columns (2) / missing (<0)
            VCD_temp[sza_temp>88] = np.nan
            VCD_filtered[:,:,k] = VCD_temp
        VCD_avg = np.nanmean(VCD_filtered, axis=2)
        data_yr[:, list_doy(i)] = VCD_avg.flatten() # Put daily data as column vector
        print (f'OMHCHOG_{yr}_{list_doy[i]:03d}')
        
        if list_doy[i]%50==0:
            data_sub = data_yr[:, list_doy[i]-48:list_doy[i]]
            sio.savemat(os.path.join(data_path, 'pre', 'OMI_L3_tempConv', f'OMHCHOG_{yr}_{list_doy[i]:03d}.mat'), mdict={'data_sub':data_sub})
    # Gathering part files
    data_yr = []
    for m in range(50, 350+1, 50):
        data_sub = sio.loadmat(os.path.join(data_path, 'pre', 'OMI_L3_tempConv', f'OMHCHOG_{yr}_{list_doy[i]:03d}.mat'))
        data_yr = np.concatenate((data_yr, data_sub), axis=1) # data_yr=[data_yr,data_sub];
    data_sub = sio.loadmat(os.path.join(data_path, 'pre', 'OMI_L3_tempConv', f'OMHCHOG_{yr}_end.mat'))
    data_yr = np.concatenate((data_yr, data_sub), axis=1)
        
    data_yr(isnan(data_yr))=-9999;
    prefix = np.tile('d', [days, 1]) # prefix for header
    header = map(lambda x: f'{x:03d}', prefix) # header = cellstr([prefix,num2str([1:days]','%03i')]);
    sio.savemat(os.path.join(data_path, 'OMI_L3_tempConv', f'OMHCHOG_{yr}_DU.mat'), mdict={'data_yr':data_yr})

SyntaxError: can't assign to function call (<ipython-input-11-1f2a8d6f6173>, line 23)